-- Lsp configs
require("lsp.config.diagnostic-ls")
require("lsp.config.python-ls")
require("lsp.config.bash-ls")
require("lsp.config.html-ls")
require("lsp.config.lua-ls")
require("lsp.config.tsserver-ls")
require("lsp.config.vim-ls")
require("lsp.config.cpp-ls")
require("lsp.config.jsonls")
require("lsp.config.deluge-ls")
require("lsp.config.css-ls")
require("lsp.config.sql-ls")
require("lsp.config.ltex-ls")
require("lsp.config.emmet")
require("lsp.config.docker-ls")
require("lsp.config.tailwindcss-ls")
