require('plugins.ui.lualine')
-- require('plugins.ui.lualine2')
require('plugins.ui.colorizer')
require('plugins.ui.bufferline')
require('plugins.ui.web-devicons')
require('plugins.ui.nonicons')
require('plugins.ui.lspkind')
require('plugins.ui.whichkey')
require('plugins.ui.gitsigns')
require('plugins.ui.rainbow')
require('plugins.ui.zen')
require('plugins.ui.neoscroll')
