require('plugins.ui.lualine')
require('plugins.ui.colorizer')
require('plugins.ui.bufferline')
require('plugins.ui.web-devicons')
require('plugins.ui.nonicons')
require('plugins.ui.lspkind')
require('plugins.ui.whichkey')
-- require('plugins.ui.rainbow')
