print("Loading tools.init.lua")
--[[ require('plugins.tools.vimwiki')
require('plugins.tools.kommentary')
require('plugins.tools.vim-rooter')
require('plugins.tools.telescope')
require('plugins.tools.telescope-functions') ]]
-- require('plugins.tools.floaterm')
-- require('plugins.tools.yankhighlight')
-- require('plugins.tools.markdown-preview')
-- require('plugins.tools.startify')
