require('plugins.themes.gruvbox-flat')
-- require('plugins.themes.global')
-- require('plugins.themes.gruvbox-nvim')
-- require('plugins.themes.gruvbox-community')
-- require('plugins.themes.tokyonight')
-- require('plugins.themes.dracula')
-- require('plugins.themes.spaceduck')
-- require('plugins.themes.solarized')
-- require('plugins.themes.one-nvim')
